#!/bin/bash

# Commit all changes
ci() {
    git add . && git commit -m "$*"
}

# Commit all changes and push them
cip() {
    git add . && git commit -m "$*" && git push
}

# Move git tag
git-move-tag() {
    git tag -d $1 && \
    git push --delete origin $1 && \
    git tag -a $1 -m "$1" && \
    git push origin $1
}