#!/bin/bash

ci() {
    git add . && git commit -m "$*"
}

cip() {
    git add . && git commit -m "$*" && git push
}

git_move_tag() {
    git tag -d $1 && \
    git push --delete origin $1 && \
    git tag -a $1 -m "$1" && \
    git push origin $1
}